#!/bin/bash

# https://wiki.libvirt.org/page/Networking#Forwarding_Incoming_Connections

case "${1}" in
"centos7_minimal_x64")
    # Update the following variables to fit your setup
    GUEST_IP='192.168.122.76'
    GUEST_PORT=80
    HOST_PORT=8081

    if [ "${2}" = "stopped" ] || [ "${2}" = "reconnect" ]; then
        /sbin/iptables -D FORWARD -o virbr0 -d  $GUEST_IP -j ACCEPT
        /sbin/iptables -t nat -D PREROUTING -p tcp --dport $HOST_PORT -j DNAT \
                                                   --to $GUEST_IP:$GUEST_PORT
    fi

    if [ "${2}" = "start" ] || [ "${2}" = "reconnect" ]; then
        /sbin/iptables -I FORWARD -o virbr0 -d  $GUEST_IP -j ACCEPT
        /sbin/iptables -t nat -I PREROUTING -p tcp --dport $HOST_PORT -j DNAT \
                                                   --to $GUEST_IP:$GUEST_PORT
    fi
    ;;
esac
